
#+OPTIONS: ':t *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK")
#+OPTIONS: date:t e:t email:nil f:t inline:t num:t p:nil pri:nil
#+OPTIONS: prop:nil stat:t tags:t tasks:t tex:t timestamp:t title:t
#+OPTIONS: toc:nil todo:t |:t
#+OPTIONS: num:nil

#+TITLE: Pre/Post-Test
#+SUBTITLE: Political Science 209-905 & 209-906
#+DATE: \today
#+AUTHOR: Florian Hollenbach
#+EMAIL: fhollenbach@tamu.edu
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.3.1 (Org mode 9.1.9)

#+LATEX_HEADER: \documentclass{article}
#+LATEX_HEADER: \usepackage[letterpaper, margin=1.0in]{geometry}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \doublespacing
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage[english]{isodate}
#+LATEX_HEADER: \usepackage{amsmath,amsthm,amssymb,amsfonts}

* Question 1
   TRUE or FALSE: Scientists can directly observe whether one event caused another.

a) TRUE

b) FALSE

* Question 2
  What is the average of the following list of numbers? 3 13 2 7 10 1

a) 5

b) 6

c) 8

d) 6.5

e) 10


* Question 3
  What is the median of the following list of numbers? 47 51 49 48 52

a) 47

b) 49.5

c) 51

d) 49

e) 52


* Question 3
 What method allows us to infer that the association between X and Y is actually causal (or perhaps just due to chance)?

a) Random Sampling

b) Randomized Control Trials


* Question 4 - Fill in the blank
  Compared to randomized experiments, observational studies are more likely to have compromised [blank] while their [blank] is often stronger.

a) internal validity, external validity

b) external validity, internal validity

* Question 5

The sample standard deviation is a measure of

a) the number of observations in the sample

b) how representative the sample is

c) how far away data points are, on average, from their mean

d) the average of a sample


* Question 6
  In a histogram, the height of each bin represents

a) the share of total observations that fall within the bin

b) the number of observation that fall within the bin

c) the proportion of observations within each bin divided by the width of the bin

d) none of the above

* Question 7
  The correlation coefficient between x and y measures

a) the causal effect of x on y

b) the linear association between two variables

c) how much y causes x


* Question 8

  A combination bike lock has 4 different dials with 9 numbers each. How many different four-digit passcodes can be set?

a) $9^4 =  6561$

b) $9*4 = 20$

c) $4^9 = 262144$

d) $4+9 = 13$
